-- Table structure for ra_security_data_recycle_log
CREATE TABLE `ra_security_data_recycle_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `admin_id` int unsigned NOT NULL DEFAULT '0' COMMENT '操作管理员',
  `recycle_id` int unsigned NOT NULL DEFAULT '0' COMMENT '回收规则ID',
  `data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '回收的数据',
  `data_table` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '数据表',
  `connection` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '数据库连接配置标识',
  `primary_key` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '数据表主键',
  `is_restore` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否已还原:0=否,1=是',
  `ip` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '操作者IP',
  `useragent` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'User-Agent',
  `create_time` bigint unsigned DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='数据回收记录表';

-- Data for ra_security_data_recycle_log
INSERT INTO `ra_security_data_recycle_log` VALUES ('1', '1', '4', '{\"id\":26,\"name\":\"aaa\",\"group\":\"authentication\",\"title\":\"aaa\",\"tip\":\"aaa\",\"type\":\"checkbox\",\"value\":null,\"content\":\"{\\\"key1\\\":\\\"value1\\\",\\\"key2\\\":\\\"value2\\\"}\",\"rule\":\"\",\"extend\":\"style: {display: state.form[driver] === jwt ? block : none}\",\"allow_del\":1,\"weigh\":0}', 'config', '', 'id', '0', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36', '1746914650');
INSERT INTO `ra_security_data_recycle_log` VALUES ('2', '1', '4', '{\"id\":28,\"name\":\"dddd\",\"group\":\"authentication\",\"title\":\"dddd\",\"tip\":\"\",\"type\":\"radio\",\"value\":null,\"content\":\"{\\\"key1\\\":\\\"value1\\\",\\\"key2\\\":\\\"value2\\\"}\",\"rule\":\"required\",\"extend\":\"\",\"allow_del\":1,\"weigh\":0}', 'config', '', 'id', '0', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36', '1746916110');
INSERT INTO `ra_security_data_recycle_log` VALUES ('3', '1', '4', '{\"id\":27,\"name\":\"sddf\",\"group\":\"authentication\",\"title\":\"saf\",\"tip\":\"\",\"type\":\"checkbox\",\"value\":null,\"content\":\"{\\\"key1\\\":\\\"value1\\\",\\\"key2\\\":\\\"value2\\\"}\",\"rule\":\"\",\"extend\":\"{\\\"class\\\":\\\"dddd\\\",\\\"style\\\":\\\"{display: \'none\'}\\\"}\",\"allow_del\":1,\"weigh\":0}', 'config', '', 'id', '0', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36', '1746916119');
INSERT INTO `ra_security_data_recycle_log` VALUES ('4', '1', '4', '{\"id\":37,\"name\":\"aaa\",\"group\":\"authentication\",\"title\":\"aaa\",\"tip\":\"aa\",\"type\":\"textarea\",\"value\":null,\"content\":null,\"rule\":\"\",\"extend\":\"{\\\"blockHelp\\\":\\\"1. \\\\u63a8\\\\u8350JWT,\\\\u4e0d\\\\u5b58\\\\u50a8\\\\u65e0\\\\u72b6\\\\u6001,\\\\u66f4\\\\u5b89\\\\u5168   2. Cache\\\\u65b9\\\\u5f0f\\\\u652f\\\\u6301File,Redis\\\\u7b49\\\"}\",\"allow_del\":1,\"weigh\":0}', 'config', '', 'id', '0', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36', '1746924614');
INSERT INTO `ra_security_data_recycle_log` VALUES ('5', '1', '4', '{\"id\":40,\"name\":\"aaaa\",\"group\":\"authentication\",\"title\":\"aaa\",\"tip\":\"\",\"type\":\"password\",\"value\":null,\"content\":null,\"rule\":\"\",\"extend\":\"{\\\"baInputExtend\\\":{\\\"size\\\":\\\"large\\\"}}\",\"allow_del\":1,\"weigh\":0}', 'config', '', 'id', '0', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36', '1746928365');
INSERT INTO `ra_security_data_recycle_log` VALUES ('6', '1', '5', '{\"id\":3,\"group_id\":2,\"username\":\"aaa222\",\"nickname\":\"aa222\",\"email\":\"\",\"mobile\":\"\",\"avatar\":\"\",\"gender\":0,\"birthday\":null,\"money\":0,\"score\":0,\"last_login_time\":null,\"last_login_ip\":\"\",\"login_failure\":0,\"join_ip\":\"\",\"join_time\":null,\"motto\":\"\",\"password\":\"$2y$10$jMz5Cp421brpZdn58KtG2eGPF4XV\\/ZtJQxZ8oQItFOIDhSHDT8mq2\",\"salt\":\"\",\"status\":\"enable\",\"update_time\":1747004166,\"create_time\":1747004166}', 'user', 'mysql', 'id', '0', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36', '1747008056');
INSERT INTO `ra_security_data_recycle_log` VALUES ('7', '1', '4', '{\"id\":44,\"name\":\"terminal\",\"group\":\"system\",\"title\":\"自定义命令行命令\",\"tip\":\"命令名称=>命令\",\"type\":\"array\",\"value\":\"[{\\\"key\\\":\\\"data_backup\\\",\\\"value\\\":\\\"php webman backup:all\\\"},{\\\"key\\\":\\\"test\\\",\\\"value\\\":\\\"php -v\\\"}]\",\"content\":null,\"rule\":\"\",\"extend\":\"\",\"allow_del\":1,\"weigh\":0}', 'config', '', 'id', '0', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36', '1747076102');
